// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  NEWAPI_KEY: any;
  NEWAPAI_USER: string;
  NEWAPI_URL: any;
  NEWAPI: any;
  SERV00: any;
  CORP: any;
  URL: any;
  RAINYUN_API: any;
}
